### ISSUE TITLE
Consider dropping the postinstall script and just using package.json

### ISSUE THREAD

**Issue by latentflip** [jeffboyus/pnnl-component-loader#2]
I'm not really seeing the benefit of not listing the core deps in package.json. Particularly as you only have one dependency that's not a core dep (for which you could just use the lodash core dep anyway).

By not listing them, you're effectively having to recreate how npm works, by using a post install script to install the deps. And on top of that - it won't actually work when pnnl-component-loader is installed as a dependency of something else, since the `npm` module won't be installed so the postinstall script will fail anyway.

By putting it in package.json, you can just build externalExports.js from package.json, and your externals file (which we might want to grab for webpack, can just become:

```javascript
//externals.js
var package = require('./package.json');
module.exports = Object.keys(package.dependencies)
```

**Comment by jeffboyus** [comment]
Complete on internal repo.  I had thought that making the deps be in the package.json would dirty the file and make this thing bloated. Still need to be aware of this per component when I go to make them.
