### ISSUE TITLE
Simplify tests with tape-catch

### ISSUE THREAD

**Issue by latentflip** [jeffboyus/pnnl-component-loader#3]
You can make your tests simpler/easier to read with [tape-catch](https://github.com/michaelrhodes/tape-catch) it basically wraps all the try/catch stuff for you, and throws uncaught errors as test failures.

All you have to do is add tape-catch as a dev-dependency, and `require('tape-catch')` instead of `require('tape')` in your tests (you still need tape installed too though).

So you can replace:

```javascript
test('registering a component', function (t) {
    try {
        let MyComponent = { name:'Test Component' };
        Loader.register('TestWidget', MyComponent);
        t.ok(Loader.loadedComponents['TestWidget'], 'test widget exists');
    } catch(e) {
        t.fail(e);
    } finally {
        t.end();
    }
});
```

with

```javascript
test('registering a component', function (t) {
        let MyComponent = { name:'Test Component' };
        Loader.register('TestWidget', MyComponent);
        t.ok(Loader.loadedComponents['TestWidget'], 'test widget exists');
        t.end();
});
```

**Comment by jeffboyus** [comment]
I don't know why I didn't use this. I have used it before.  Fixed all of this. Plus I fixed another issue where I EXPECT an error to be thrown. Fixed it to use the throws function in tape.
